In [150]:
import numpy as np
import scipy.constants as c 
from scipy.optimize import curve_fit
import scipy

In [79]:
Lambda = np.array([[30.4, 25.6, 24.3, 23.4],
                   [243.0, 205.0, 194.4, 189.8]]) * 1e-9
E_exp = c.h * c.c / Lambda
# E_r = lambda n, mu, Z:  - mu * Z**2 * c.e**4 / (32 * np.pi**2 * c.epsilon_0**2 * c.hbar * n**2)
E = lambda n, m, mu, Z:  - 13.6 * Z**2 * c.e * mu * (1/n**2 - 1/m**2)

In [58]:
fit, cov = curve_fit(E, np.arange(2,6), Lambda[0], [1,1],)
print(fit)

[1. 1.]


C:\Users\Lucac\AppData\Local\Temp\ipykernel_4148\4128584954.py:1: OptimizeWarning: Covariance of the parameters could not be estimated
  fit, cov = curve_fit(E, np.arange(2,6), Lambda[0], [1,1],)


In [47]:
E(5, 1, 1) / c.elementary_charge

13.056

In [219]:
print(E_exp/c.e)
# Z, mi = 2,1

Z, mi = 1,1
eV = E(np.arange(mi+1,mi+5), mi, 1/(1 - c.m_e / (2*c.m_p + 2*c.m_n)), Z) / c.e
l = c.c / (eV * c.e / c.h) * 1e9
print(eV)
print()

def f(x):
    mi = 1
    Z = 1
    eV = E(np.arange(mi+1,mi+5), mi, 1/(1 - c.m_e /x / (2*c.m_p + 2*c.m_n)), Z) / c.e
    return np.sum((eV-E_exp[1] / c.e)**2)

print(l-Lambda[1]*1e9)
# 8-8
# 
print(scipy.optimize.minimize(f, 1))

[[40.7842758  48.43132751 51.02230388 52.98470019]
 [ 5.10223039  6.04800968  6.37778799  6.5323603 ]]
[10.20138801 12.09053393 12.75173501 13.05777665]

[-121.46340286 -102.45349616  -97.17072229  -94.84953348]
  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 145.64330860662034
        x: [ 9.105e+01]
      nit: 17
      jac: [-5.722e-06]
 hess_inv: [[ 1.226e+06]]
     nfev: 36
     njev: 18
